version: 1
disable_existing_loggers: no
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logfile.log
root:
  level: INFO
  handlers: [console, file]
  propagate: yes

loggers:
  numba:
    level: INFO

